set(glew_DIR ${CMAKE_SOURCE_DIR}/lib/glew)
set(GLEW_INCLUDE_DIRS ${glew_DIR}/include)
if(WIN32)
	set(GLEW_LIBS ${glew_DIR}/lib/glew.lib)
elseif(APPLE)
	set(GLEW_LIBS ${glew_DIR}/lib/libglew.dylib)
else()
	set(GLEW_LIBS ${glew_DIR}/lib/libglew.so)
endif()
INCLUDE_DIRECTORIES(${GLEW_INCLUDE_DIRS})
list(APPEND LINK_LIBS ${GLEW_LIBS})
#add_definitions(-DGLEW_STATIC)